# Generated by Django 2.2.1 on 2019-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
